# Generated by Django 4.2.3 on 2023-07-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perfil", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conta",
            name="banco",
            field=models.CharField(
                choices=[
                    ("NU", "Nubank"),
                    ("CE", "Caixa econômica"),
                    ("IT", "Itaú"),
                    ("BB", "Banco do Brasil"),
                    ("OF", "Oficial Ouro Fino"),
                    ("BR", "Bradesco"),
                    ("IN", "Banco Inter"),
                ],
                max_length=2,
            ),
        ),
    ]
